services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./app/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./app/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SQL_INIT_MODE: always
      SPRING_FLYWAY_ENABLED: "false"
    ports:
      - "8080:8080"

volumes:
  db-data:
    driver: local

