FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /src

COPY pom.xml ./
RUN mvn dependency:go-offline -B

COPY . .
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /src/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]

